logging:
  destination: \Neuron\Log\Destination\File
  format: \Neuron\Log\Format\PlainText
  file: test.log
  level: debug

views:
  path: views

system:
  timezone: US/Eastern
  base_path: examples
