request:
  method: POST
  headers:
    Content-Type: application/json
  properties:
    array:
      required: true
      type: array
    boolean:
      required: true
      type: boolean
    date:
      required: true
      type: date
    date_time:
      required: true
      type: date_time
    ein:
      required: true
      type: ein
    email:
      required: true
      type: email
    float:
      required: true
      type: float
    integer:
      required: true
      type: integer
      range:
        min: 1
        max: 100
    ip_address:
      required: true
      type: ip_address
    name:
      required: true
      type: name
    numeric:
        required: true
        type: numeric
    object:
      required: true
      type: object
      properties:
        subparam1:
          required: true
          type: string
          length:
            min: 3
            max: 20
        subparam2:
          required: true
          type: string
          length:
            min: 3
            max: 20
    string:
      required: true
      type: string
      length:
        min: 3
        max: 20
    time:
      required: true
      type: time
    upc:
      required: true
      type: upc
    url:
      required: true
      type: url
    us_phone:
      required: true
      type: us_phone_number
    intl_phone:
      required: true
      type: intl_phone_number
